---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '11:00'
    groups:
      all:
        patterns:
          - "*"  # Group all updates into a single larger pull request.

  # Maintain Go module dependencies
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      time: '11:00'
    groups:
      all:
        patterns:
          - "*"  # Group all updates into a single larger pull request.